# Generated by Django 5.1.5 on 2025-08-03 05:50

import i18nutils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_default', models.CharField(default=None, max_length=255, null=True, verbose_name='name (default)')),
                ('name_en', models.CharField(default=None, max_length=255, null=True, verbose_name='name (en)')),
                ('name_en_us', models.CharField(default=None, max_length=255, null=True, verbose_name='name (en-us)')),
                ('name_it', models.CharField(default=None, max_length=255, null=True, verbose_name='name (it)')),
                ('name_es', models.CharField(default=None, max_length=255, null=True, verbose_name='name (es)')),
                ('name_fr', models.CharField(default=None, max_length=255, null=True, verbose_name='name (fr)')),
                ('name_de', models.CharField(default=None, max_length=255, null=True, verbose_name='name (de)')),
                ('description_default', models.TextField(default=None, null=True, verbose_name='description (default)')),
                ('description_en', models.TextField(default=None, null=True, verbose_name='description (en)')),
                ('description_en_us', models.TextField(default=None, null=True, verbose_name='description (en-us)')),
                ('description_it', models.TextField(default=None, null=True, verbose_name='description (it)')),
                ('description_es', models.TextField(default=None, null=True, verbose_name='description (es)')),
                ('description_fr', models.TextField(default=None, null=True, verbose_name='description (fr)')),
                ('description_de', models.TextField(default=None, null=True, verbose_name='description (de)')),
            ],
            bases=(i18nutils.models.TranslatableModelMixin, models.Model),
        ),
    ]
