# Generated by Django 5.1.5 on 2026-03-10 09:11

import i18nutils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JSONProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    i18nutils.fields.JSONi18nCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    i18nutils.fields.JSONi18nTextField(blank=True, null=True),
                ),
            ],
        ),
    ]
