# Generated by Django 5.1.5 on 2026-03-10 13:50

import i18nutils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0002_jsonproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsonproduct",
            name="name",
            field=i18nutils.fields.JSONi18nCharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
