# Generated by Django 5.1.5 on 2026-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0003_alter_jsonproduct_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name_de",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="name (de)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_default",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="name (default)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="name (en)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en_us",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="name (en-us)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_es",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="name (es)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_fr",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="name (fr)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_it",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="name (it)",
            ),
        ),
    ]
